kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "kamus.name" . }}-controller
rules:
- apiGroups: ["soluto.com"] # "" indicates the core API group
  resources: ["kamussecrets"]
  verbs: ["watch"]
- apiGroups: ["soluto.com"]
  resources: ["kamussecrets/finalizers"]
  verbs: ["update"]
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets"]
  verbs: ["create", "delete", "patch"]
