name: CI
on: [pull_request, push]
jobs:
  lint-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint
        run: shellcheck -x test/e2e-kind.sh

  lint-charts:
    runs-on: ubuntu-latest
    container:
      image: docker://quay.io/helmpack/chart-testing:v2.2.0 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint
        run: ct lint --config test/ct.yaml
  
  install-charts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: install
        run: ./test/e2e-kind.sh 